### PR TITLE
Add User Routes

### PR DESCRIPTION
**Pull request by seancorc**
* Add routes for getting, deleting, and updating a user.

* Check to ensure the uniqueness of a netID upon user creation and update.

### CODE REVIEW

**Comment by grebneerg** [comment]
Is this app intended to be limited to only Cornell students? If so, I imagine you are planning to add some validation of netIDs, but if not it seems strange to have the a field in every user called `netID`.

**Comment by seancorc** [comment]
> Is this app intended to be limited to only Cornell students? If so, I imagine you are planning to add some validation of netIDs, but if not it seems strange to have the a field in every user called `netID`.

It is intended to be limited to only Cornell students. Good point about validating netIDs, I'll look into it.

**Review by grebneerg — APPROVED** [review]

**Review by orkosinha — APPROVED** [review]
lgtm

**Comment by orkosinha** [comment]
> Is this app intended to be limited to only Cornell students? If so, I imagine you are planning to add some validation of netIDs, but if not it seems strange to have the a field in every user called `netID`.

Mobile is going to validate that the email is a Cornell email. The routes themselves are going to be changed later to support some form of authentication.

**Pull request merged**
