### PR TITLE
Prepare for Testflight Launch

### PR DESCRIPTION
**Pull request by chalo2000**
## Overview

After learning that the memory issue with the server was due to `relations` receiving too many arguments for `UserRepo.getUsers`, there had to be some refactoring done to avoid this. 

One relevant refactor included adding separate GET requests #42 for each user field that involved an entity, which helps frontend better structure their models to make them more concrete and intuitive. An abstract GET where arguments for the entities desired was considered, but the possibility of crashing the server if too many entities are desired made me scrap this idea.

Another refactor was for `UserRepo.getUsers` and `UserRepo.getUser`. Since frontend wanted to improve their models, these functions now return a friendlier `SerializedCommunityUser` which returns just the information necessary to display on the Weekly Pear and Community Screen. Since there are only 3 entities (major, interests, groups) included in `relations` we aren't threatened by server crash. **However**, pagination #48 still needs to be added to `getUsers` which can be done before new organizations get on Pear.

The last change was for the Matcher, which runs every 2 minutes for iOS to test effectively before it is changed to run weekly at some time on Monday to be determined.

Also added organizations #46 that will be partaking in our Testflight soon.

## Changes Made

- Small docker-compose.server.yml change to reflect what is on the server
- 8 GET requests added for the respective POST requests used to update those categories
  - To facilitate this, `UserRepo.getUser` was updated to take in a specific relation which can be passed in by other repos trying to access a user's entity attribute
- `SerializedCommunityUser` created to return to frontend just what they need in `UserRepo.getUsers` and `UserRepo.getUser`
- Matcher is back online
  - Inefficient - right now gets all users' netIDs which gets users with relevant matching attributes but does not cache users after retrieval -> TODO
  - Hacky - need to wait for additional features such as Opt Out or multiple matches for odd sized user bases to work, so just taking myself out for the time being in case the user base is odd to make it even

## Test Coverage

[Pear Testing.postman_collection.json.zip](https://github.com/cuappdev/pear-backend/files/6017201/Pear.Testing.postman_collection.json.zip)

Edited the Postman collection to get user attributes through the 8 GETs and all test cases passed. In addition, ensured that matches are randomly assigned and still function when there are an odd number of users (including myself, since I am taken out to make it even)

## Next Steps

#41 would make frontend's life easier and then #48 will make retrieving users much quicker when opening the Community Screen and when searching on it

## Related PRs or Issues

#42 #46

### CODE REVIEW

**Review by alanna-zhou — APPROVED** [review]
nice! could you update the `docker-compose.server.yml` to remove `build: .`?

**Review by alanna-zhou — CHANGES_REQUESTED** [review]
seems like @lucyxubroad does not want this to be merged

**Comment by chalo2000** [comment]
> seems like @lucyxubroad does not want this to be merged

Yup the model changes would be unrealistic for launch tomorrow, I changed a serialization function so there are now two ways of accessing information so iOS has drastically less to refactor now before tomorrow and a good amount of work to do with refactoring later on in the week!

**Review by alanna-zhou — APPROVED** [review]

**Review by tedim52 — APPROVED** [review]
LGTM, good work Gonzalo. Very detailed explanations as well

**Pull request merged**
